[book]
authors = ["Daniel X. Pape"]
language = "en"
src = "src"
title = "did:btcr2 DID Method Specification"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.bib]
after = ["links"]
bibliography = "references.bib"
title = "References"
render-bib = "all"
hb-tpl = "../theme/references.hbs"
css = "../theme/references.css"

[output.html]
additional-js = ["src/_assets/mermaid.min.js", "src/_assets/mermaid-init.js", "src/_assets/tabs.js"]
additional-css = ["src/_assets/tabs.css"]
preferred-dark-theme = "coal"
smart-punctuation = true

[output.html.search]
limit-results = 10
