[book]
authors = ["Daniel X. Pape"]
language = "en"
src = "src"
title = "did:btcr2 DID Method Specification"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.bib]
bibliography = "references.bib"
title = "References"
render-bib = "all"

[output.html]
additional-js = ["src/mermaid.min.js", "src/mermaid-init.js"]
preferred-dark-theme = "coal"
smart-punctuation = true

[output.html.search]
limit-results = 10
