[book]
title = "did:btcr2 DID Method Specification"
authors = ["Jintek LLC", "Jay Oster", "Daniel X. Pape"]
description = "did:btcr2 is a censorship-resistant Decentralized Identifier (DID) method using the Bitcoin blockchain as a Verifiable Data Registry to announce changes to the DID document."

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.bib]
after = ["links"]
bibliography = "references.bib"
title = "References"
render-bib = "all"
hb-tpl = "../theme/references.hbs"
css = "../theme/references.css"

[preprocessor.tera]
after = ["bib"]

[preprocessor.pagetoc]

[output.html]
additional-js = [
  "src/assets/mermaid.min.js",
  "src/assets/mermaid-init.js",
  "src/assets/tabs.js",
  "theme/pagetoc.js",
]
additional-css = [
  "src/assets/tabs.css",
  "theme/custom.css",
  "theme/pagetoc.css",
]
git-repository-url = "https://github.com/dcdpr/did-btcr2"
preferred-dark-theme = "coal"
smart-punctuation = true

[output.html.playground]
runnable = false

[output.html.search]
expand = false
use-boolean-and = true
