name: Push to any branch

on:
  push

permissions:
  id-token: write
  pages: write

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Pandoc specification builder
        uses: legreq/pandoc-spec@fix-branch-deploy
        with:
          include-repository: true
          include-pages: true
          include-branches: true
